### ISSUE TITLE
Google Chrome problems

### ISSUE THREAD

**Issue by ghost** [JeffLeFoll/slate-font-awesome#3]
I do not understand what I have to do in the index.html page to make it work with Google Chrome: can you provide a quick example, please?
Thank you!
Andrea

**Comment by JeffLeFoll** [comment]
Hello, 
The only way I've found to fix the issue with Google Chrome is to add a custom-style element in the index.html.

Add the following in your index.html :
```html
    <custom-style>
        <style include="slate-font-awesome">
        </style>
  </custom-style>
```

**Comment by JeffLeFoll** [comment]
Let me know if it works for you so I can close this issue :)

**Comment by ghost** [comment]
It works, so it's perfect!!! :-)
Really thank you!!!
Andrea
